from common import *
W="ffffff"; B="101820"; R="d71920"; N="1c2b4a"; CEL="6cb4e4"; V="00843d"; A="1c3a8f"; Y="f5c400"
lpf=[
C("aldosivi","Aldosivi","ALD",K(Y,V,Y,"stripes",V),K(W,W,W),"José María Minella",35354,-3),
C("argentinos","Argentinos Juniors","ARG",K(R,W,R),K(W,W,W),"Diego Armando Maradona",26000,1),
C("atltucuman","Atlético Tucumán","ATU",K(CEL,B,W,"stripes",W),K(B,B,B),"Monumental José Fierro",35200,-1),
C("banfield","Banfield","BAN",K(W,W,W,"stripes",V),K(V,V,V),"Florencio Sola",34901,-2),
C("barracas","Barracas Central","BAR",K(R,W,R,"stripes",W),K(W,W,W),"Claudio Chiqui Tapia",4400,-2),
C("belgrano","Belgrano","BEL",K(CEL,B,CEL),K(W,W,W),"Julio César Villagra",38000,1),
C("boca","Boca Juniors","BOC",K("0a2a6e","0a2a6e","0a2a6e","band",Y),K(W,W,W,"band","0a2a6e"),"La Bombonera",54000,6,keeper=Y),
C("centralcba","Central Córdoba (SdE)","CCO",K(B,B,B,"stripes",W),K(W,W,W),"Madre de Ciudades",30000,-2),
C("defensa","Defensa y Justicia","DYJ",K(Y,V,Y,"halves",V),K(V,V,V),"Norberto Tomaghello",18000,0),
C("estudiantes","Estudiantes de La Plata","EDL",K(R,B,R,"stripes",W),K(W,W,W),"Jorge Luis Hirschi",30018,3),
C("gimnasia","Gimnasia y Esgrima La Plata","GEL",K(W,W,W,"band",N),K(N,N,N),"Juan Carmelo Zerillo",21500,-1),
C("godoycruz","Godoy Cruz","GCR",K(A,W,A,"stripes",W),K(W,W,W),"Malvinas Argentinas",42000,-2),
C("huracan","Huracán","HUR",K(W,W,W),K(R,R,R),"Tomás Adolfo Ducó",48314,1),
C("independiente","Independiente","IND",K(R,W,R),K(W,W,W),"Libertadores de América",42069,2),
C("indriv","Independiente Rivadavia","IRM",K(A,W,A),K(W,W,W),"Bautista Gargantini",24000,-1),
C("instituto","Instituto","INS",K(R,W,R,"stripes",W),K(W,W,W),"Juan Domingo Perón",26535,-2),
C("lanus","Lanús","LAN",K("7a1f3d",W,"7a1f3d"),K(W,W,W),"Ciudad de Lanús",47027,2),
C("newells","Newell's Old Boys","NOB",K(R,B,R,"halves",B),K(W,W,W),"Marcelo Bielsa",42000,0),
C("platense","Platense","PLA",K(W,W,W,"band","5a3a24"),K("5a3a24","5a3a24","5a3a24"),"Ciudad de Vicente López",28530,0),
C("racing","Racing Club","RAC",K(CEL,B,W,"stripes",W),K(B,B,B),"Presidente Perón (El Cilindro)",55880,4),
C("river","River Plate","RIV",K(W,B,W,"sash",R),K(R,B,R,"sash",B),"Mâs Monumental",85018,6),
C("rosariocentral","Rosario Central","ROS",K(A,A,A,"stripes",Y),K(Y,A,Y),"Gigante de Arroyito",41654,2),
C("sanlorenzo","San Lorenzo","SLO",K(A,W,A,"stripes",R),K(W,W,W),"Pedro Bidegain (Nuevo Gasómetro)",47964,1),
C("sanmartinsj","San Martín de San Juan","SMS",K(V,B,V,"stripes",B),K(W,W,W),"Hilario Sánchez",19000,-3),
C("sarmiento","Sarmiento de Junín","SAR",K(V,W,V),K(W,W,W),"Eva Perón",22000,-3),
C("talleres","Talleres de Córdoba","TAL",K(A,A,A,"stripes",W),K(W,W,W),"Mario Alberto Kempes",57000,2),
C("tigre","Tigre","TIG",K(A,W,A,"band",R),K(W,W,W),"José Dellagiovanna",26282,0),
C("union","Unión de Santa Fe","UNI",K(R,W,R,"stripes",W),K(W,W,W),"15 de Abril",28000,-1),
C("velez","Vélez Sarsfield","VEL",K(W,A,W,"v",A),K(A,A,A,"v",W),"José Amalfitani",49540,3),
C("riestra","Deportivo Riestra","RIE",K(B,B,B),K(W,W,W),"Guillermo Laza",3000,-3),
]
pn=[
C("allboys","All Boys","ALB",K(W,B,W),K(B,B,B),"Islas Malvinas",21500),
C("almagro","Almagro","ALM",K(A,B,A,"stripes",B),K(W,W,W),"Tres de Febrero",19000),
C("almbrown","Almirante Brown","ABR",K(Y,B,B,"stripes",B),K(W,W,W),"Fragata Presidente Sarmiento",15000),
C("agropecuario","Agropecuario","AGR",K(A,W,A),K(W,W,W),"Ofelia Rosenzuaig",4000),
C("arsenal","Arsenal de Sarandí","ARS",K(CEL,CEL,CEL,"sash",R),K(W,W,W),"Julio Humberto Grondona",16300,1),
C("atlanta","Atlanta","ATL",K(Y,A,Y,"stripes",A),K(W,W,W),"Don León Kolbowski",14000),
C("rafaela","Atlético de Rafaela","RAF",K(CEL,W,CEL,"stripes",W),K(W,W,W),"Monumental de Barrio Alberdi",16000),
C("chacarita","Chacarita Juniors","CHA",K(R,B,B,"stripes",B),K(W,W,W),"Chacarita Juniors",19000),
C("chacoforever","Chaco For Ever","CFE",K(B,B,B,"stripes",W),K(W,W,W),"Juan Alberto García",23000),
C("colegiales","Colegiales","COL",K(A,A,A,"stripes",R),K(W,W,W),"Libertarios Unidos",4000),
C("colon","Colón","COL",K(R,B,R,"halves",B),K(W,W,W),"Brigadier General Estanislao López",40000,2),
C("defbelgrano","Defensores de Belgrano","DEF",K(R,B,R,"stripes",B),K(W,W,W),"Juan Pasquale",8000),
C("madryn","Deportivo Madryn","MAD",K(B,B,B,"stripes",W),K(W,W,W),"Abel Sastre",4500),
C("moron","Deportivo Morón","MOR",K(W,R,W),K(R,R,R),"Nuevo Francisco Urbano",32000),
C("estcaseros","Estudiantes de Buenos Aires","EBA",K(B,B,B,"stripes",W),K(W,W,W),"Ciudad de Caseros",16740),
C("estrc","Estudiantes de Río Cuarto","ERC",K(W,B,W,"band",A),K(A,A,A),"Antonio Candini",15000),
C("ferro","Ferro Carril Oeste","FER",K(V,W,V),K(W,W,W),"Arquitecto Ricardo Etcheverri",24442,1),
C("gimmendoza","Gimnasia y Esgrima (Mendoza)","GIM",K(W,B,W,"stripes",B),K(B,B,B),"Víctor Antonio Legrotaglie",11000),
C("gimtiro","Gimnasia y Tiro","GYT",K(W,CEL,W,"band",CEL),K(CEL,CEL,CEL),"Gigante del Norte",20000),
C("guemes","Güemes","GUE",K(CEL,W,CEL),K(W,W,W),"Arturo Miranda",10000),
C("mitre","Mitre (Santiago del Estero)","MIT",K(Y,B,Y,"stripes",B),K(W,W,W),"José y Antonio Castiglione",11000),
C("chicago","Nueva Chicago","NCH",K(V,B,V,"stripes",B),K(W,W,W),"República de Mataderos",28500),
C("patronato","Patronato","PAT",K(R,B,R,"stripes",B),K(W,W,W),"Presbítero Bartolomé Grella",22000),
C("quilmes","Quilmes","QUI",K(W,A,W),K(A,A,A),"Centenario",30200,1),
C("racingcba","Racing de Córdoba","RCO",K(CEL,W,CEL,"stripes",W),K(W,W,W),"Miguel Sancho",17000),
C("smtucuman","San Martín de Tucumán","SMT",K(R,W,R,"stripes",W),K(W,W,W),"La Ciudadela",30250,1),
C("sanmiguel","San Miguel","SMI",K(Y,V,Y,"stripes",V),K(W,W,W),"Malvinas Argentinas (San Miguel)",4000),
C("santelmo","San Telmo","STE",K(CEL,CEL,CEL,"band",W),K(W,W,W),"Osvaldo Baletto",5000),
C("tallereRE","Talleres de Remedios de Escalada","TRE",K(R,W,R,"band",W),K(W,W,W),"Talleres de Remedios de Escalada",8000),
C("temperley","Temperley","TEM",K(CEL,W,CEL),K(W,W,W),"Alfredo Beranger",22000),
C("tristan","Tristán Suárez","TSU",K(B,B,B,"stripes",Y),K(W,W,W),"20 de Octubre",5000),
C("maipu","Deportivo Maipú","MAI",K(R,B,R,"stripes",B),K(W,W,W),"Higinio Sperdutti",9000),
C("alvarado","Alvarado","ALV",K(A,W,A,"stripes",W),K(W,W,W),"José María Minella",35354),
C("bolivar","Ciudad de Bolívar","CBO",K(CEL,N,CEL),K(W,W,W),"Municipal de Bolívar",6000),
C("centralnorte","Central Norte","CNO",K(B,B,B,"stripes",W),K(W,W,W),"Dr. Luis Güemes",14000),
C("losandes","Los Andes","LAN",K(W,R,W,"band",R),K(R,R,R),"Eduardo Gallardón",36000),
]
b=[
C("acassuso","Acassuso","ACA",K(CEL,A,CEL),K(W,W,W),"Gerardo Gaetano",4500),
C("argquilmes","Argentino de Quilmes","AQU",K(CEL,W,CEL,"stripes",W),K(W,W,W),"Argentino de Quilmes",4000),
C("armenio","Deportivo Armenio","ARM",K(W,W,W,"hoops",R),K(R,R,R),"Armenia",8000),
C("brown","Brown de Adrogué","BRO",K(Y,B,Y,"stripes",B),K(W,W,W),"Lorenzo Arandilla",4500),
C("canuelas","Cañuelas","CAN",K(R,W,R,"stripes",W),K(W,W,W),"Jorge Alberto Cañuelas",3000),
C("comunicaciones","Comunicaciones","COM",K(Y,B,Y,"stripes",B),K(W,W,W),"Alfredo Ramos",3500),
C("docksud","Dock Sud","DOC",K(B,B,B,"hoops",W),K(W,W,W),"de los Inmigrantes",4000),
C("excursionistas","Excursionistas","EXC",K(V,W,V,"hoops",W),K(W,W,W),"Excursionistas",7200),
C("fenix","Fénix","FEN",K(W,B,W),K(B,B,B),"Carlos Barraza",3000),
C("flandria","Flandria","FLA",K(V,W,V,"stripes",W),K(W,W,W),"Carlos V",4500),
C("ituzaingo","Ituzaingó","ITU",K(V,W,V,"stripes",W),K(W,W,W),"Carlos Alberto Sacaan",3500),
C("jjurquiza","J. J. Urquiza","URQ",K(W,W,W,"band",A),K(A,A,A),"Ramón Pedro Ferrari",2500),
C("sacachispas","Sacachispas","SAC",K("7a3fa0",W,"7a3fa0"),K(W,W,W),"Beto Larrosa",2000),
C("italiano","Sportivo Italiano","ITA",K(A,W,A),K(W,W,W),"República de Italia",8000),
C("uai","UAI Urquiza","UAI",K(W,W,W,"band",R),K(R,R,R),"Monte Castro",1500),
C("dalmine","Villa Dálmine","VDA",K("7a1f3d",W,"7a1f3d","stripes",W),K(W,W,W),"El Coliseo de Mitre y Puccini",10000),
C("villasancarlos","Villa San Carlos","VSC",K(CEL,W,CEL,"stripes",W),K(W,W,W),"Genacio Sálice",4500),
C("merlo","Deportivo Merlo","MER",K(CEL,W,CEL),K(W,W,W),"José Manuel Moreno",6000),
C("realpilar","Real Pilar","RPI",K(R,B,R),K(W,W,W),"Real Pilar",2500),
C("laferrere","Deportivo Laferrere","LAF",K(V,W,V,"stripes",W),K(W,W,W),"Laferrere",4000),
]
c=[
C("atlas","Atlas","ATL",K(B,B,B,"stripes",Y),K(W,W,W),"Ricardo Puga",3000),
C("berazategui","Berazategui","BER",K(V,W,V,"stripes",W),K(W,W,W),"Norman Lee",3000),
C("centralros","Central Córdoba (Rosario)","CCR",K(A,W,A,"stripes",R),K(W,W,W),"Gabino Sosa",8000),
C("centroespanol","Centro Español","CES",K(R,W,R,"band",Y),K(W,W,W),"Centro Español",1500),
C("claypole","Claypole","CLA",K(W,W,W,"band",R),K(R,R,R),"Rodolfo Capocasa",2000),
C("depespanol","Deportivo Español","ESP",K(R,W,R,"band",Y),K(W,W,W),"Nueva España",32500),
C("cambaceres","Defensores de Cambaceres","CAM",K(R,W,R,"stripes",W),K(W,W,W),"Defensores de Cambaceres",4000),
C("elporvenir","El Porvenir","POR",K(W,B,W,"stripes",B),K(B,B,B),"Gildo Francisco Ghersinich",15000),
C("midland","Ferrocarril Midland","MID",K(CEL,N,CEL),K(W,W,W),"Ferrocarril Midland",3000),
C("lamadrid","General Lamadrid","LAM",K(R,W,R,"stripes",W),K(W,W,W),"Enrique Sexto",2000),
C("juventudunida","Juventud Unida","JUN",K(W,A,W),K(A,A,A),"Juventud Unida",2000),
C("alem","Leandro N. Alem","ALE",K(V,W,V,"stripes",W),K(W,W,W),"Leandro N. Alem",3000),
C("lujan","Luján","LUJ",K(W,W,W,"band",A),K(A,A,A),"Luján",4000),
C("burzaco","San Martín de Burzaco","SMB",K(R,W,R,"stripes",W),K(W,W,W),"San Martín",3000),
C("barracasbol","Sportivo Barracas","SBA",K(W,R,W,"band",R),K(R,R,R),"Luciano Coppola",1500),
C("victoriano","Victoriano Arenas","VAR",K(CEL,W,CEL,"stripes",W),K(W,W,W),"Saturnino Moure",2000),
C("yupanqui","Yupanqui","YUP",K(W,W,W,"band",R),K(R,R,R),"Yupanqui",1500),
C("muniz","Muñiz","MUN",K(A,W,A),K(W,W,W),"Muñiz",1500),
C("argmerlo","Argentino de Merlo","AME",K(CEL,W,CEL,"stripes",W),K(W,W,W),"Argentino de Merlo",3000),
C("lugano","Club Lugano","LUG",K(CEL,W,CEL),K(W,W,W),"Lugano",1500),
C("paraguayo","Deportivo Paraguayo","PAR",K(R,A,W,"stripes",W),K(W,W,W),"Deportivo Paraguayo",1500),
C("puertonuevo","Puerto Nuevo","PNU",K(CEL,W,CEL),K(W,W,W),"Puerto Nuevo",1000),
C("argrosario","Argentino de Rosario","ARO",K(A,W,A,"stripes",W),K(W,W,W),"Gabino Sosa",3000),
C("liniers","Club Social y Deportivo Liniers","LIN",K(W,R,W),K(R,R,R),"Liniers",1500),
]
write("arg","Argentina","arg","es_ar",[55,40,4,1],[
 D("arg1","Liga Profesional",1,lpf,"2026"), D("arg2","Primera Nacional",2,pn,"2026"),
 D("arg3","Primera B Metropolitana",3,b,"2026"), D("arg4","Primera C",4,c,"2026")])
